name: Docker Image CI

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --tag barn3y95/pdapp:latest .
    - name: Push the Docker image
      run: |
        docker login -u barn3y95 -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push barn3y95/pdapp:latest
